name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Inject Environment Variables into application.properties
        run: |
          sed -i "s/server.port=.*/server.port=${SERVER_PORT}/" src/main/resources/application.properties
          sed -i "s/dispatch.ip=.*/dispatch.ip=${DISPATCH_IP}/" src/main/resources/application.properties
          sed -i "s/spring.datasource.url=.*/spring.datasource.url=${DB_URL}/" src/main/resources/application.properties
          sed -i "s/spring.datasource.username=.*/spring.datasource.username=${DB_USERNAME}/" src/main/resources/application.properties
          sed -i "s/spring.datasource.password=.*/spring.datasource.password=${DB_PASSWORD}/" src/main/resources/application.properties
          sed -i "s/spring.s3.accessKey=.*/spring.s3.accessKey=${S3_ACCESSKEY}/" src/main/resources/application.properties
          sed -i "s/spring.s3.secretKey=.*/spring.s3.secretKey=${S3_SECRETKEY}/" src/main/resources/application.properties
          sed -i "s/iamport.api_key=.*/iamport.api_key=${API_KEY}/" src/main/resources/application.properties
          sed -i "s/iamport.api_secret=.*/iamport.api_secret=${API_SECRET}/" src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Additional steps for Docker build and deployment
