name: Java CI with Gradle and Docker Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v2

      - name: JDK 17 설정
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle로 빌드
        run: ./gradlew clean build -x test

      - name: Docker 이미지 빌드
        run: |
          docker build -t my-cupet-boot-main .
          docker tag my-cupet-boot-main mydockerhubusername/my-cupet-boot-main:latest

      - name: Docker 레지스트리 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 레지스트리에 푸시
        run: docker push mydockerhubusername/my-cupet-boot-main:latest

      - name: NCP에 배포
        run: |
          curl -X POST \
            -H "Authorization: Basic ${{ secrets.NCP_AUTH }}" \
            -H "Content-Type: application/json" \
            -d '{"image": "mydockerhubusername/my-cupet-boot-main:latest", "name": "my-cupet-boot-main", "port": 9090}' \
            https://ncloud.apigw.ntruss.com/vserver/v2/startServerInstances

      - name: 환경 변수 설정
        run: |
          echo "SERVER_PORT=9090" >> $GITHUB_ENV
          echo "DISPATCH_IP=${{ secrets.DISPATCH_IP }}" >> $GITHUB_ENV
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "S3_ACCESSKEY=${{ secrets.S3_ACCESSKEY }}" >> $GITHUB_ENV
          echo "S3_SECRETKEY=${{ secrets.S3_SECRETKEY }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "API_SECRET=${{ secrets.API_SECRET }}" >> $GITHUB_ENV
