name: Java CI with Gradle and Docker Deploy

on:
  push:
    branches:
      - main  # 배포하려는 브랜치 이름으로 변경 가능
  pull_request:
    branches:
      - main  # 풀 리퀘스트가 올라오면 테스트 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    env:
      DOCKER_IMAGE_NAME: my-cupet-boot-main  # Docker 이미지 이름
      DOCKER_REGISTRY: starsong0422/starsongrepo  # Docker Hub 레지스트리 이름

    steps:
      - name: Checkout 소스 코드
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      #환경변수 설정
      - name: Inject Environment Variables into application.properties
        run: |
          echo "server.port=${SERVER_PORT}" >> src/main/resources/application.properties
          echo "dispatch.ip=${DISPATCH_IP}" >> src/main/resources/application.properties
          echo "db.url=${DB_URL}" >> src/main/resources/application.properties
          echo "db.username=${DB_USERNAME}" >> src/main/resources/application.properties
          echo "db.password=${DB_PASSWORD}" >> src/main/resources/application.properties
          echo "s3.accesskey=${S3_ACCESSKEY}" >> src/main/resources/application.properties
          echo "s3.secretkey=${S3_SECRETKEY}" >> src/main/resources/application.properties
          echo "api.key=${API_KEY}" >> src/main/resources/application.properties
          echo "api.secret=${API_SECRET}" >> src/main/resources/application.properties

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME .
          docker tag $DOCKER_IMAGE_NAME $DOCKER_REGISTRY:latest

      - name: Login to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to registry
        run: docker push $DOCKER_REGISTRY:latest

      - name: Deploy to NCP
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          SIGNATURE=$(echo -n "${TIMESTAMP}${NCP_ACCESS_KEY}${NCP_SECRET_KEY}" | openssl dgst -sha256 -hmac "${NCP_SECRET_KEY}" -binary | base64)
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-ncp-apigw-api-key: ${NCP_ACCESS_KEY}" \
            -H "x-ncp-iam-signature-v2: ${SIGNATURE}" \
            -H "x-ncp-apigw-timestamp: ${TIMESTAMP}" \
            -d '{
                  "image": "'"$DOCKER_REGISTRY:latest"'",
                  "name": "your-app-name"
                }' \
            https://ncloud.apigw.ntruss.com/vserver/v2/startServerInstances

      - name: Set Environment Variables
        run: |
          echo "NCP_ACCESS_KEY=${NCP_ACCESS_KEY}" >> $GITHUB_ENV
          echo "NCP_SECRET_KEY=${NCP_SECRET_KEY}" >> $GITHUB_ENV
